### ISSUE TITLE
Arch Linux LenovoLegionLinux won't launch after install, No module named 'legion_linux'

### ISSUE THREAD

**Issue by Linkachus17** [johnfanv2/LenovoLegionLinux#214] opened 2024-05-01 12:55 UTC
### System Info
Lenovo Legion 5 15ARH05H
Arch Linux (6.8.8-arch1-1)

### Issue
- Won't launch after either installing it from AUR or building it using ```make```
```
$ legion_cli
Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 5, in <module>
    from legion_linux.legion_cli import main
ModuleNotFoundError: No module named 'legion_linux'
```

- ```lenovolegionlinux-dkms-git``` on AUR is having problem when installing (might be unrelated but I think I should point it out)
```
...
(4/4) LenovoLegionLinux.hook
warning: LenovoLegionLinux: Cannot perform the requested operation due to missing package(s).
```

**Comment by jiang131072** [comment] 2024-05-04 10:15
The script is here : [deploy/LenovoLegionLinux](https://github.com/johnfanv2/LenovoLegionLinux/blob/cba5b7043f58c2f577b46c56a61e0143708c4e8e/deploy/LenovoLegionLinux#L16).
It checks the installation of mkinitcpio and dracut, however the mkinitcpio branch is commented out. Logic here is strange.

**Comment by st0nie** [comment] 2024-05-05 03:49
Yeah, the hook is broken and should be removed
CC @MrDuartePT
We'd like to accept a patch to fix the `PKGBUILD`

**Comment by MrDuartePT** [comment] 2024-05-05 11:05
> The script is here : [deploy/LenovoLegionLinux](https://github.com/johnfanv2/LenovoLegionLinux/blob/cba5b7043f58c2f577b46c56a61e0143708c4e8e/deploy/LenovoLegionLinux#L16). It checks the installation of mkinitcpio and dracut, however the mkinitcpio branch is commented out. Logic here is strange.

Basically I comment wrong, should haven't only comment line 13 to prevent mkinitcpio of running twices (basically arch already has a hook that run mkinitcpio when a out-of-kernel tree module is install.
I very strange this error being reported after 7 month I did the commit tho

**Comment by MrDuartePT** [comment] 2024-05-05 11:10
> ```
> $ legion_cli
> Traceback (most recent call last):
>   File "/usr/bin/legion_cli", line 5, in <module>
>     from legion_linux.legion_cli import main
> ModuleNotFoundError: No module named 'legion_linux'
> ```

Now this error I don't understand why it happen please check if legion_linux is available on legion_linux python install directory. Since the AUR `PKGBUILD` is base on the gentoo ebuild and the gentoo ebuild is still working fine

**Comment by MrDuartePT** [comment] 2024-05-05 11:32
@st0nie @Linkachus17 looking at the action logs the aur should give that error: https://github.com/johnfanv2/LenovoLegionLinux/actions/runs/8957813959/job/24601322012#step:3:4340

The arch linux container install the packages by cloning the aur repo.

**Comment by MrDuartePT** [comment] 2024-05-05 11:42
I can not reproduce this error on a fresh manjaro vm, and since the github action also don't have the error I would assume is your arch install and the PKGBUILD is working fine
![image](https://github.com/johnfanv2/LenovoLegionLinux/assets/68701049/29586cf7-59bc-4207-b401-2c8a95554707)

Closing since is not a bug LLL

**Closed by MrDuartePT** 2024-05-05 11:42 UTC

**Comment by MrDuartePT** [comment] 2024-05-05 11:53
@Linkachus17 seems that arch linux change to python3.12 recently you probably need to uninstall and install LLL again

**Comment by Linkachus17** [comment] 2024-05-05 12:41
I can confirm that there's something wrong with my Arch install previously, not sure why. I reinstalled my Arch last night and now LLL works fine
![image](https://github.com/johnfanv2/LenovoLegionLinux/assets/50126684/adfbd7e2-a1ec-4b7f-871b-16b3af990023)

**Comment by PinkSerenity** [comment] 2024-06-09 12:20
I had the same error. I think it's related to this:
```
Module version  for legion-laptop.ko.zst
exactly matches what is already found in kernel 6.9.3-arch1-1.
DKMS will not replace this module.
You may override by specifying --force.
Error! Installation aborted.
==> WARNING: `dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.9.3-arch1-1' exited 6
```
Running `dkms install --no-depmod --force lenovolegionlinux/1.0.0 -k 6.9.3-arch1-1` seemed to fix it for me.

**Comment by MrDuartePT** [comment] 2024-06-09 13:14
> I had the same error. I think it's related to this:

No, it not related since is the module and not Python app

> 
> ```
> 
> Module version  for legion-laptop.ko.zst
> 
> exactly matches what is already found in kernel 6.9.3-arch1-1.
> 
> DKMS will not replace this module.
> 
> ```

If you read the message carefully, it explains you already have the module install so dkms will not replace it.

**Comment by PinkSerenity** [comment] 2024-06-09 14:44
> No, it not related since is the module and not Python app

Doesn't the Python app depend on the module?
> If you read the message carefully, it explains you already have the module install so dkms will not replace it.

Yeah, which is why I `--force`d it. I think maybe the previous module didn't properly get removed when I un-installed and reinstalled the package. So I always had the apparently corrupted module, and only like this I was able to replace it.

By the way, I also deleted the LLL directory in `/var/libs/dkms/`. I remember that I once updated the Nvidia driver and an old directory remained there, so mkinitcpio complained about a missing config.

**Comment by unkindypie** [comment] 2025-01-25 21:01
I get the same error after system update now, was working before
```
➜  ~ legion_gui
Traceback (most recent call last):
  File "/usr/bin/legion_gui", line 5, in <module>
    from legion_linux.legion_gui import main
ModuleNotFoundError: No module named 'legion_linux'

```

**Comment by bannert1337** [comment] 2025-01-28 16:25
I deleted `/var/libs/dkms/` and then installed `lenovolegionlinux-dkms-git` from `cachyos` and got this error:
```shell
DKMS make.log for lenovolegionlinux/1.0.0 for kernel 6.13.0-2-cachyos (x86_64)
Di 28. Jan 17:14:17 CET 2025
make -C /lib/modules/6.13.0-2-cachyos/build M=/var/lib/dkms/lenovolegionlinux/1.0.0/build modules
make[1]: Entering directory '/usr/lib/modules/6.13.0-2-cachyos/build'
make[2]: Entering directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
  CC [M]  legion-laptop.o
legion-laptop.c:5683:6: warning: variable 'err' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
 5683 |         if (!priv->adev) {
      |             ^~~~~~~~~~~
legion-laptop.c:5709:9: note: uninitialized use occurs here
 5709 |         return err;
      |                ^~~
legion-laptop.c:5683:2: note: remove the 'if' if its condition is always false
 5683 |         if (!priv->adev) {
      |         ^~~~~~~~~~~~~~~~~~
 5684 |                 dev_info(dev, "Could not get ACPI handle\n");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5685 |                 goto err_acpi_init;
      |                 ~~~~~~~~~~~~~~~~~~~
 5686 |         }
      |         ~
legion-laptop.c:5677:9: note: initialize the variable 'err' to silence this warning
 5677 |         int err;
      |                ^
      |                 = 0
legion-laptop.c:6146:3: error: field designator 'remove_new' does not refer to any field in type 'struct platform_driver'
 6146 |         .remove_new = legion_remove,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[4]: *** [/usr/lib/modules/6.13.0-2-cachyos/build/scripts/Makefile.build:194: legion-laptop.o] Error 1
make[3]: *** [/usr/lib/modules/6.13.0-2-cachyos/build/Makefile:1997: .] Error 2
make[2]: *** [/usr/lib/modules/6.13.0-2-cachyos/build/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.13.0-2-cachyos/build'
make: *** [Makefile:13: all] Error 2
```
